version: '3.8'
services:
  dev-db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    networks:
    - back-db_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  back-end:
    container_name: ${BACK_END_CONTAINER_NAME}
    env_file:
      - .env
      - back-end/.env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_CONTAINER_NAME}:${DB_PORT}/${DB_NAME}?schema=public
    build:
      context: ./back-end
    depends_on:
      - dev-db
    ports:
      - ${BACK_END_PORT}:3333
      - ${PRISMA_MONITOR_PORT}:5555
    networks:
    - front-back_network
    - back-db_network
  front-end:
    container_name: ${FRONT_END_CONTAINER_NAME}
    build:
      context: ./front-end
    ports:
      - ${FRONT_END_PORT}:3000
    depends_on:
      - back-end
    networks:
    - front-back_network
networks:
  front-back_network:
  back-db_network:
volumes:
  postgres_data:
    external: ${DB_IS_EXTERNAL}
    name: ${DB_VOLUME_NAME}